apiVersion: v1
kind: Service
metadata:
  name: frontend
  spec:
    type: NodePort
    selector:
      tier: frontend
      app: dice
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      NodePort: 31000