apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ProjectFrontEnd
spec:
  replicas: 2
  template:
    metadata:
      labels:
        tier: frontend
        app: dice
    spec:
      containers:
      - name: frontend
        image: bilalbokharee/diceproject01
        ports:
        - containerPort: 8080
          name: tcp